version: "3.9"

services:
  caddy:
    build: .
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy_data:/data
      - ./caddy_config:/config
      - ./conf.d:/etc/caddy/conf.d
    environment:
      CF_API_TOKEN: "${CF_API_TOKEN}"
      CADDY_INGRESS_NETWORKS: caddy_net
      LOG_LEVEL: "info"
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true
